const resources = [
    {
        image: "aceturnity.png",
        link: "https://ui.aceternity.com/",
        title: "Aceturnity",
        description: "Copy paste the most trending components and use them in your websites without having to worry about styling and animations.",
        tag: "Libraries",
    },
    {
        image: "awwwards.png",
        link: "https://www.awwwards.com/",
        title: "Awwwards",
        description: "The awards that recognize the talent and effort of the best web designers, developers and agencies in the world.",
        tag: "Inspiration",
    },
    {
        image: "oliverlarose.png",
        link: "https://blog.olivierlarose.com/",
        title: "Oliver Larose's Blog",
        description: "Gallery of creative web development components crafted by Oliver Larose.",
        tag: "Libraries",
    },
    {
        image: "codegrid.png",
        link: "https://www.youtube.com/@codegrid",
        title: "Codegrid",
        description: "New video Sundays and Wednesdays",
        tag: "Youtubers",
    },
    {
        image: "rotato.png",
        link: "https://rotato.app/iphone/iphone-12-toss-up",
        title: "Rotato",
        description: "Everything you need to make slick mockups for your showcases.",
        tag: "Mockups",
    },
    {
        image: "shadcn.png",
        link: "https://ui.shadcn.com/",
        title: "Shadcn UI",
        description: "Beautifully designed components that you can copy and paste into your apps. Made with Tailwind CSS. Open source.",
        tag: "Libraries",
    },
    {
        image: "lawsofux.png",
        link: "https://lawsofux.com/",
        title: "Laws of UX",
        description: "Laws of UX is a collection of best practices that designers can consider when building user interfaces.",
        tag: "Guidelines",
    },
    {
        image: "framer.png",
        link: "https://www.framer.com/marketplace/templates/category/free/?via=andresthedesigner&fp_sid=youtube",
        title: "Framer",
        description: "Find the best free templates, customize easily and create a professional website without cost. Pick from various designs and features. All templates are HTML, responsive & browser-friendly.",
        tag: "Inspiration",
    },
    {
        image: "uicolors.png",
        link: "https://uicolors.app/create",
        title: "UI Colors",
        description: "Press spacebar, enter a hexcode or change the HSL values to create a custom color scale",
        tag: "Brand",
    },
    {
        image: "cursor.png",
        link: "https://cursor.design/",
        title: "Cursor",
        description: "Copy macOS cursors with ease.",
        tag: "Libraries",
    },
    {
        image: "shots.png",
        link: "https://shots.so/",
        title: "Shots.so",
        description: "Embrace the ease of designing with Shots. Create beautiful mockups in seconds, giving you more time to focus on your original design.",
        tag: "Mockups",
    },
    {
        image: "designpatterns.png",
        link: "https://catalogue.projectsbyif.com/",
        title: "Design Patterns Catalogue",
        description: "IF curates this catalogue to help teams design trustworthy services that work for people. Contact IF for workshops about how to use these patterns.",
        tag: "Guidelines",
    },
    {
        image: "dcs.png",
        link: "https://www.doingcoolstuff.xyz/",
        title: "Doing Cool Stuff",
        description: "A directory of brand, motion and digital product design studios doing cool stuff.",
        tag: "Inspiration",
    },
    {
        image: "wearedigitalmakers.png",
        link: "https://www.youtube.com/@wadm_space",
        title: "We Are Digital Makers",
        description: "A community-driven brand focused on empowering developers and designers to create modern and efficient websites.",
        tag: "Youtubers",
    },
    {
        image: "brandfetch.png",
        link: "https://brandfetch.com/",
        title: "BrandFetch",
        description: "The internet’s source for logos and brand assets.",
        tag: "Brand",
    },
    {
        image: "freefaces.png",
        link: "https://www.freefaces.gallery/?3a2d1f52_page=3",
        title: "Free Faces",
        description: "This website is a curated collection of typefaces that are available under a variety of free licences somewhere on the interwebs.",
        tag: "Brand",
    },
    {
        image: "freemockup.png",
        link: "https://www.free-mockup.com/",
        title: "Free Mockup",
        description: "An extensive collection of free photorealistic Mockups online! Easily customizable PSD mockups ready for your projects and app presentations. Updates every day.",
        tag: "Mockups",
    },
    {
        image: "patternclub.png",
        link: "https://patternclub.io/",
        title: "Pattern Club",
        description: "A curated gallery to find pattern inspiration",
        tag: "Brand",
    },
    {
        image: "grainient.png",
        link: "https://grainient.supply/freebies",
        title: "Grainient.",
        description: "Over 1000+ High Quality, grainy textured and smooth gradient backgrounds. Elevate your designs with Grainients.",
        tag: "Brand",
    },
    {
        image: "osmo.png",
        link: "https://www.osmo.supply/",
        title: "Osmo",
        description: "Osmo is an exclusive platform for everyone looking to stand out as a creative developer in our digital industry.",
        tag: "Libraries",
    },
    {
        image: "navbargallery.png",
        link: "https://www.navbar.gallery/",
        title: "Navbar Gallery",
        description: "Find the best navigation bar examples for your design.",
        tag: "Inspiration",
    },
    {
        image: "akram.png",
        link: "https://www.youtube.com/@WrongAkram/videos",
        title: "Akram",
        description: "",
        tag: "Youtubers",
    },
    {
        image: "frontendfyi.png",
        link: "https://www.youtube.com/@frontendfyi/videos",
        title: "Frontend FYI",
        description: "Teaching you the craft in frontend.",
        tag: "Youtubers",
    },
    {
        image: "coolors.png",
        link: "https://coolors.co/",
        title: "Coolors",
        description: "Create the perfect palette or get inspired by thousands of beautiful color schemes.",
        tag: "Brand",
    },
    {
        image: "oliverlaroseyt.png",
        link: "https://www.youtube.com/@olivierlarose1/videos",
        title: "Oliver Larose",
        description: "Hey there👋",
        tag: "Youtubers",
    },
    {
        image: "uidesign.png",
        link: "https://designvault.io/type/ui/",
        title: "UI Inspiration",
        description: "Looking for inspiration for your next project? Unleash your creativity by exploring an ever-growing collection of designs and common user interface patterns from the world’s best products and designers.",
        tag: "Inspiration",
    },
    {
        image: "theocodetech.png",
        link: "https://www.youtube.com/@codebytheo/videos",
        title: "Theo CodeTech",
        description: "This channel is talking about programming, especially about website. code with some technology from javascript or else.",
        tag: "Youtubers",
    },
];

export default resources;